
Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-gt5bq[0m
{"level":"info","ts":1593209008.9007351,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593209008.901286,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-9wjjj[0m
{"level":"info","ts":1593209010.2256536,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593209010.2275674,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-ablazleon-jxpy-pr-34-pr-build-qg7t9-jl28x[0m
{"level":"info","ts":1593209018.2790298,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593209020.1020966,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*********/**py.git @ master in path /workspace/source"}

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:35c67ec9b58d1146d2c36ce8e3cdc34479e36046,34:aba4511e94e5a22c1745ae9bb0fbe22863fc4841
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow aba4511e94e5a22c1745ae9bb0fbe22863fc4841: 35c67ec9b58d1146d2c36ce8e3cdc34479e36046:
DEBUG: ran git fetch --unshallow origin aba4511e94e5a22c1745ae9bb0fbe22863fc4841: 35c67ec9b58d1146d2c36ce8e3cdc34479e36046: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 35c67ec9b58d1146d2c36ce8e3cdc34479e36046
DEBUG: ran git reset --hard 35c67ec9b58d1146d2c36ce8e3cdc34479e36046 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge aba4511e94e5a22c1745ae9bb0fbe22863fc4841
DEBUG: ran git merge aba4511e94e5a22c1745ae9bb0fbe22863fc4841 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e 35c67ec9b58d1146d2c36ce8e3cdc34479e36046..HEAD
Merged SHA aba4511e94e5a22c1745ae9bb0fbe22863fc4841 with commit message 'Update README.md' into base branch master

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0626 22:03:44.342131       9 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0001] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0001] Retrieving image manifest python:onbuild     
E0626 22:03:44.775370       9 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0626 22:03:44.777950       9 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[36mINFO[0m[0002] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Built cross stage deps: map[]                
[36mINFO[0m[0004] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Retrieving image manifest python:onbuild     
[36mINFO[0m[0005] Executing 3 build triggers                   
[36mINFO[0m[0005] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:dc2a839bd6d525fd9783a6852939774c55dc14024a49397cd18ef840aae363e1... 
[36mINFO[0m[0006] Using caching version of cmd: COPY requirements.txt /usr/src/app/ 
[36mINFO[0m[0006] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:8bf2abf0a84228eb1cc03999f3ee3ce7361230c16e28eae7af74285f6291b7d4... 
[36mINFO[0m[0007] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0007] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:16ffa994380bc37ccb0bfa5033342e24c8130c4405a644a6a799142a1b874ae9... 
[36mINFO[0m[0008] No cached layer found for cmd COPY . /usr/src/app 
[36mINFO[0m[0008] cmd: EXPOSE                                  
[36mINFO[0m[0008] Adding exposed port: 8080/tcp                
[36mINFO[0m[0008] Unpacking rootfs as cmd COPY . /usr/src/app requires it. 
[36mINFO[0m[0033] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0033] Found cached layer, extracting to filesystem 
[36mINFO[0m[0033] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0033] Found cached layer, extracting to filesystem 
[36mINFO[0m[0034] COPY . /usr/src/app                          
[36mINFO[0m[0035] Resolving 131 paths                          
[36mINFO[0m[0035] Taking snapshot of files...                  
[36mINFO[0m[0035] Pushing layer gcr.io/envjenkinsk8udacitycapstone/cache:16ffa994380bc37ccb0bfa5033342e24c8130c4405a644a6a799142a1b874ae9 to cache now 
[36mINFO[0m[0035] COPY requirements.txt .                      
[36mINFO[0m[0035] Resolving 1 paths                            
[36mINFO[0m[0035] Taking snapshot of files...                  
[36mINFO[0m[0035] ENV PORT 8080                                
[36mINFO[0m[0035] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0035] EXPOSE 8080                                  
[36mINFO[0m[0035] cmd: EXPOSE                                  
[36mINFO[0m[0035] Adding exposed port: 8080/tcp                
[36mINFO[0m[0035] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0035] ENTRYPOINT ["python"]                        
[36mINFO[0m[0035] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0035] CMD ["app.py"]                               
[36mINFO[0m[0035] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0035] Pushing layer gcr.io/envjenkinsk8udacitycapstone/cache:cf0c1b1e472258c64f54dd3f277f3cccf8a605cef0f20b9530bf48c2ce2c19b7 to cache now 

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-34-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-34-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: gcr.io\/envjenkinsk8udacitycapstone\/**py|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-34-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-34-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mablazleon-jxpy-pr-34-pr-build-qg7t9-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Found commit author match for: ********* with email address: adrian.blazquez.leon@alumnos.upm.es
Created environment *********-**py-pr-34
Namespace **-*********-**py-pr-34 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 34.91.102.68.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: gcr.io/envjenkinsk8udacitycapstone/**py
    tag: 0.0.0-SNAPSHOT-PR-34-1

Updating PipelineActivities *********-**py-pr-34-1 which has status Running
WARNING: preview application http://**py.**-*********-**py-pr-34.34.91.102.68.nip.io not available, error was Get http://**py.**-*********-**py-pr-34.34.91.102.68.nip.io: dial tcp 34.91.102.68:80: connect: connection refused, delaying for: 783.034151ms
WARNING: preview application http://**py.**-*********-**py-pr-34.34.91.102.68.nip.io not available, error was Get http://**py.**-*********-**py-pr-34.34.91.102.68.nip.io: dial tcp 34.91.102.68:80: connect: connection refused, delaying for: 1.077829579s
Preview application is now available at: http://**py.**-*********-**py-pr-34.34.91.102.68.nip.io
