
Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-pbkj2[0m
{"level":"info","ts":1593181626.254493,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593181626.2554414,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-nscg7[0m
{"level":"info","ts":1593181627.3058252,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593181627.307449,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-ablazleon-jxpy-pr-6-pr-build-flqsz-knxtk[0m
{"level":"info","ts":1593181646.2779737,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593181648.4137251,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*********/**py.git @ master in path /workspace/source"}

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:1f5af3e66b84fe199102311f0b8d7db89ca7fd52,6:4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9: 1f5af3e66b84fe199102311f0b8d7db89ca7fd52:
DEBUG: ran git fetch --unshallow origin 4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9: 1f5af3e66b84fe199102311f0b8d7db89ca7fd52: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 1f5af3e66b84fe199102311f0b8d7db89ca7fd52
DEBUG: ran git reset --hard 1f5af3e66b84fe199102311f0b8d7db89ca7fd52 in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9
DEBUG: ran git merge 4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e 1f5af3e66b84fe199102311f0b8d7db89ca7fd52..HEAD
Merged SHA 4f69b2af3f66a8d4d4a8b1d82b66e0dd630295d9 with commit message 'Update app.py' into base branch master

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0626 14:27:33.141158      10 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0001] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0001] Retrieving image manifest python:onbuild     
E0626 14:27:33.685343      10 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0626 14:27:33.688860      10 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[36mINFO[0m[0003] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Built cross stage deps: map[]                
[36mINFO[0m[0004] Retrieving image manifest python:onbuild     
[36mINFO[0m[0005] Retrieving image manifest python:onbuild     
[36mINFO[0m[0006] Executing 3 build triggers                   
[36mINFO[0m[0006] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:dc2a839bd6d525fd9783a6852939774c55dc14024a49397cd18ef840aae363e1... 
[36mINFO[0m[0007] Using caching version of cmd: COPY requirements.txt /usr/src/app/ 
[36mINFO[0m[0007] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:8bf2abf0a84228eb1cc03999f3ee3ce7361230c16e28eae7af74285f6291b7d4... 
[36mINFO[0m[0008] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0008] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:bc3bbeead60eb4ce72754d2e9476f8453a8f736afe4bfa8e6e79a827ac138790... 
[36mINFO[0m[0008] No cached layer found for cmd COPY . /usr/src/app 
[36mINFO[0m[0008] cmd: EXPOSE                                  
[36mINFO[0m[0008] Adding exposed port: 8080/tcp                
[36mINFO[0m[0008] Unpacking rootfs as cmd COPY . /usr/src/app requires it. 
[36mINFO[0m[0024] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0024] Found cached layer, extracting to filesystem 
[36mINFO[0m[0024] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0024] Found cached layer, extracting to filesystem 
[36mINFO[0m[0027] COPY . /usr/src/app                          
[36mINFO[0m[0028] Resolving 148 paths                          
[36mINFO[0m[0028] Taking snapshot of files...                  
[36mINFO[0m[0028] COPY requirements.txt .                      
[36mINFO[0m[0028] Pushing layer gcr.io/envjenkinsk8udacitycapstone/cache:bc3bbeead60eb4ce72754d2e9476f8453a8f736afe4bfa8e6e79a827ac138790 to cache now 
[36mINFO[0m[0028] Resolving 1 paths                            
[36mINFO[0m[0028] Taking snapshot of files...                  
[36mINFO[0m[0028] ENV PORT 8080                                
[36mINFO[0m[0028] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0028] EXPOSE 8080                                  
[36mINFO[0m[0028] cmd: EXPOSE                                  
[36mINFO[0m[0028] Adding exposed port: 8080/tcp                
[36mINFO[0m[0028] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0028] ENTRYPOINT ["python"]                        
[36mINFO[0m[0028] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0028] CMD ["app.py"]                               
[36mINFO[0m[0028] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0028] Pushing layer gcr.io/envjenkinsk8udacitycapstone/cache:80ca88943b5f734114532a2ed4b4d635cc49a472a225ca2babbf621068e0ee2a to cache now 

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-6-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-6-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: gcr.io\/envjenkinsk8udacitycapstone\/**py|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-6-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-6-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mablazleon-jxpy-pr-6-pr-build-flqsz-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Found commit author match for: ********* with email address: adrian.blazquez.leon@alumnos.upm.es
Created environment *********-**py-pr-6
Namespace **-*********-**py-pr-6 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 34.91.102.68.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: gcr.io/envjenkinsk8udacitycapstone/**py
    tag: 0.0.0-SNAPSHOT-PR-6-1

Updating PipelineActivities *********-**py-pr-6-1 which has status Running
Preview application is now available at: http://**py.**-*********-**py-pr-6.34.91.102.68.nip.io
